### ISSUE TITLE
TUI TODO

### ISSUE THREAD

**Issue by ivelsantos** [ivelsantos/cryptor#22]
- [x] Implement algos creation view
- [x] Implement help view
- [x] Implement algo status change funcionality
- [x] Implement algo deletion functionality
- [x] Implement algo incorrect code signaling
- [x] Implement user creation view
- [x] Implement user deletion functionality
