### ISSUE TITLE
BACKTESTING

### ISSUE THREAD

**Issue by ivelsantos** [ivelsantos/cryptor#38]
### TODO

- [x] Make Values handle backtesting
- [x] Make Functions handle backtesting
- [x] Make Operations handle backtesting
- [x] Make Backtesting Result type
- [ ] #39
- [x] Store backtesting results on the database

**Comment by ivelsantos** [comment]
The leftovers issues are only enhancements for the Backtesting functionality, and as such, can be delayed for later milestone.

**Comment by ivelsantos** [comment]
Issue will be close because the only task leftover has it's own issue to be tracked
